#####################################模块通用配置  优先级 1.模块 2.common-xxx 3.common ########################################
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
    # Hikari 连接池配置
    type: com.zaxxer.hikari.HikariDataSource  #表明使用Druid连接池
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      autoCommit: true
      # 连接池名称
      # pool-name: MyHikariCPApp
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  resources:
    add-mappings: false #不要为我们工程中的资源文件建立映射
  jackson: # 不要开启 @EnableWebMvc 注解 会冲突  如非要开启 请使用配置类的方式重写
    #    property-naming-strategy: SNAKE_CASE   # 小驼峰转下划线
    locale: zh_CN
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    #参数意义：
    #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  application:
    #项目名
    name: @application.name@


mybatis-plus:
  configuration:
    #当设置为 true 的时候，懒加载的对象可能被任何懒属性全部加载，否则，每个属性都按需加载。需要和 lazyLoadingEnabled 一起使用
    aggressive-lazy-loading: false
    lazy-loading-enabled: false
    # map-underscore-to-camel-case: true  # 实体类里面用的是驼峰命名，数据库里面是下划线分隔命名
  mapper-locations: classpath*:mapper/*Mapper.xml # 配置xml文件扫描
  type-aliases-package: net.jinyiyun.framework.entity  # 配置实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config:
      id-type: auto  # 主键自增
      logic-delete-field: deletedAt # 全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      # 插入判断
      # insert-strategy: not_empty
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      # update-strategy: not_empty
    banner: false

#####################################测试环境 公共配置########################################
---
# 数据源配置
spring:
  profiles: dev

#####################################正式环境 公共配置########################################
---
# 数据源配置
spring:
  profiles: prod